package com.demo.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

@Data
@DynamoDBTable(tableName = "transaction_details")
public class TransactionDetails {

    @DynamoDBHashKey (attributeName = "id")
    @DynamoDBAutoGeneratedKey
    String id;

    @DynamoDBAttribute (attributeName = "bene_name")
    String beneName;

    @DynamoDBAttribute (attributeName = "amount")
    Double amount;
}
